{% set version = "2.20" %}

package:
  name: hdfeos2
  version: {{ version }}

source:
  url: 
    - ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos/latest_release/HDF-EOS{{ version }}v1.00.tar.Z
    - http://jnb.za.distfiles.macports.org/distfiles/hdfeos/HDF-EOS{{ version }}v1.00.tar.Z
  sha256: cb0f900d2732ab01e51284d6c9e90d0e852d61bba9bce3b43af0430ab5414903

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - hdf4
    - zlib
    - jpeg
  run:
    - hdf4
    - zlib
    - jpeg

test:
  commands:
    - test -f ${PREFIX}/lib/libGctp.a  # [not win]
    - test -f ${PREFIX}/lib/libhdfeos.a  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://hdfeos.org/index.php
  license: Public Domain
  summary: 'Earth Observing System HDF'

extra:
  recipe-maintainers:
    - ocefpaf
    - jhamman
