travis:
  secure:
    BINSTAR_TOKEN: zXMuOER4wYP79m+oLxHkiWVE2/dcyAdYHn3Me/gukKSmX0wDlwQuKs8o32BMeT071yOo7iz3WjMzQRTzMksEyAWeQgBxmnyV73aeFL6Lk5lOb+/zx2j8IK6vXpCsvJuqIicB3GT3TQjDCzd81ashQvqZjR5Vm9XIzGilsg1DNyeMII8kGGSGCZKdAmWNy7zM8sMBtybKApu+4i2ZeaH86iSpaZyj4Dd4+YW/uZtha5DU5Xf+3tz+ZirdCdoh+f1Isq7Kwu3wLyBb+WN6lMyIuFZgFLKr7J7geZmzktUYUHSmhd2BOH0M1kUCXkhJSn/YFwb7N7feMl4C1Mz3iAZPbLRO/CD1zwutfNP/aj/42DIuCXaNpYauGlWYNWU4iI2WGDZ4Lq1zJ4ZOiqP4PSUGTqOfbWTs/93c9Zg68iBhN+kbw870JNgzUzMaATX3+yo2/x+R+Ny58SPrN3nPkKWn8ReTrT7ZXm+fZgHCylfhGPpqaCwjg3rjq7znP7TTn+ErkygBVmOGbyY9MXw7z34myTx+qJWgnwVT56r/GIXTkyFm9b7KNC0SyqT93P5UAYVJ0rTM8PMFytREFRT4m7MnbV3+gMGhJKpvoJCqZ3Xbg0FSQroadj4OYHZ/LDIokRjqwtn3APbYzHq6ISC19X+EUIrWcoX0JB3rzLTb80EjVeE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
